Fix mds
ocha98/ac-library-java pull request #38
Opened 2024-02-28 12:18 UTC by viral8code

いくつかの md ファイルを修正しました

2024-02-29 04:41 UTC, ocha98 requested changes
英語版までありがとうございます！

気になる点としては、`articulationPoints`と`bridges`に`static`が不要です。

2024-02-29 04:41 UTC, ocha98 commented on doc/en/Graph/LowLink.md
> +public static boolean[] bridges()
```suggestion
public boolean[] bridges()
```

2024-02-29 04:41 UTC, ocha98 commented on doc/en/Graph/LowLink.md
> +public static boolean[] articulationPoints()
```suggestion
public boolean[] articulationPoints()
```

2024-02-29 04:41 UTC, ocha98 commented on doc/Graph/LowLink.md
> +public static boolean[] bridges()
```suggestion
public boolean[] bridges()
```

2024-02-29 04:41 UTC, ocha98 commented on doc/Graph/LowLink.md
> +public static boolean[] articulationPoints()
```suggestion
public boolean[] articulationPoints()
```

2024-02-29 07:13 UTC, viral8code commented
コピペがバレてしまった…
修正しました！
( Changes request されてるのに気付かないで commit してしまいました…すみません…)

2024-03-01 02:35 UTC, ocha98 approved these changes
大丈夫そうです！

2024-03-01 02:35 UTC, merged